#!/usr/bin/env bash

# fzf-presentation --- Find presentation and choose one of them using FZF
# author: Seong Yong-ju <sei40kr@gmail.com>

set -euo pipefail
IFS=$'\n\t'

find . -mindepth 1 -maxdepth 1 -type f -name '*.md' -not -name 'README.md' | fzf
